const movieDetail= [{"Title":"Guardians of the Galaxy Vol. 2","Year":"2017",
    "Released":"05 May 2017","Runtime":"136 min",
    "Genre":"Action, Adventure, Comedy, Sci-Fi","Director":"James Gunn",
    "Poster":"https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
    "BoxOffice":"$389,813,101","Production":"Marvel Studios","imdbID":"tt3896198",
    "Plot":"Quill contacts Yondu before following Gamora into space, giving her his helmet to survive; Yondu arrives and retrieves the pair. Rocket, Drax, and Groot threaten to attack Yondu's ship to rescue them, but Quill negotiates a truce, promising the orb to Yondu. Quill's group agrees that facing Ronan means certain death, but that they cannot let him use the Infinity Stone to destroy the galaxy. On Ronan's flagship, the Dark Aster, Ronan embeds the Stone in his warhammer,"
    },{
        "Title":"Avatar","Released":"18 Dec 2009","imdbID":"tt0499549",
        "Poster":"https://m.media-amazon.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
        "BoxOffice":"$389,813,101","Production":"Marvel Studios","imdbID":"tt396198",
        "Plot":"During the subsequent battle, the Na'vi suffer heavy casualties, including Tsu'tey and Trudy, but are rescued when Pandoran wildlife unexpectedly join the attack and overwhelm the humans, which Neytiri interprets as Eywa's answer to Jake's prayer. Jake destroys a makeshift bomber before it can reach the Tree of Souls; Quaritch, wearing an AMP suit, escapes from his own damaged aircraft and breaks open the avatar link unit containing Jake's human body, exposing it to Pandora's poisonous atmosphere."
    },
    {
        "Title":"Ava","Year":"2020","Rated":"R","Released":"25 Sep 2020","Runtime":"96 min","Genre":"Action, Crime, Drama, Thriller","Director":"Tate Taylor","Writer":"Matthew Newton","Actors":"Jessica Chastain, John Malkovich, Common, Geena Davis","Plot":"Ava is a deadly assassin who works for a black ops organization, traveling the globe specializing in high profile hits. When a job goes dangerously wrong she is forced to fight for her own survival.","Language":"English, French, German","Country":"USA","Awards":"N/A","Poster":"https://m.media-amazon.com/images/M/MV5BMTMzMTg1MjgtOWNhYy00NmZmLWExOTctMjA2OTZhZDFkNDhhXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"5.4/10"},{"Source":"Metacritic","Value":"39/100"}],"Metascore":"39","imdbRating":"5.4","imdbVotes":"37,064","imdbID":"tt8784956","Type":"movie","DVD":"N/A","BoxOffice":"$497,747","Production":"N/A","Website":"N/A","Response":"True"
    },
    {"Title":"The Lego Movie","Year":"2014","Rated":"PG","Released":"07 Feb 2014","Runtime":"100 min","Genre":"Animation, Action, Adventure, Comedy, Family, Fantasy","Director":"Christopher Miller, Phil Lord","Writer":"Phil Lord (screenplay by), Christopher Miller (screenplay by), Dan Hageman (story by), Kevin Hageman (story by), Phil Lord (story by), Christopher Miller (story by), Ole Kirk Christiansen (based on LEGO Construction Toys created by), Godtfred Kirk Christiansen (based on LEGO Construction Toys created by), Jens Nygaard Knudsen (based on LEGO Construction Toys created by), Peter Laird (characters created by: Teenage Mutant Ninja Turtles), Kevin Eastman (characters created by: Teenage Mutant Ninja Turtles)","Actors":"Will Arnett, Elizabeth Banks, Craig Berry, Alison Brie","Plot":"An ordinary LEGO construction worker, thought to be the prophesied as \"special\", is recruited to join a quest to stop an evil tyrant from gluing the LEGO universe into eternal stasis.","Language":"English, Turkish","Country":"USA, Denmark, Australia","Awards":"Nominated for 1 Oscar. Another 72 wins & 65 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTg4MDk1ODExN15BMl5BanBnXkFtZTgwNzIyNjg3MDE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.7/10"},{"Source":"Rotten Tomatoes","Value":"96%"},{"Source":"Metacritic","Value":"83/100"}],"Metascore":"83","imdbRating":"7.7","imdbVotes":"323,413","imdbID":"tt1490017","Type":"movie","DVD":"N/A","BoxOffice":"$257,760,692","Production":"LEGO System A/S, Lin Pictures, Vertigo","Website":"N/A","Response":"True"
    },
    {"Title":"Robert","Year":"2015","Rated":"Not Rated","Released":"24 Aug 2015","Runtime":"90 min","Genre":"Horror","Director":"Andrew Jones","Writer":"Andrew Jones","Actors":"Suzie Frances Garton, Lee Bane, Flynn Allen, Judith Haley","Plot":"In this chilling story based on real life events a family experience terrifying supernatural occurrences when their son acquires a vintage doll called Robert.","Language":"N/A","Country":"UK","Awards":"N/A","Poster":"https://m.media-amazon.com/images/M/MV5BMTg4MjUyOTUwNl5BMl5BanBnXkFtZTgwMjY1NDM2NjE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"3.1/10"}],"Metascore":"N/A","imdbRating":"3.1","imdbVotes":"1,741","imdbID":"tt4141368","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"
    },
    {"Title":"Monstar","Year":"2013","Rated":"N/A","Released":"17 May 2013","Runtime":"N/A","Genre":"Drama, Music, Romance","Director":"N/A","Writer":"N/A","Actors":"Joon-hyung Yong, Yeon-Soo Ha, Kang Ha-Neul, Min-yeong Kim","Plot":"Yoon Sul-Chan is the vocalist for the fictional group \"Man in Black\". He carries deep wounds within his mind, but doesn't express his feelings. Because of his hot temper, he causes trouble....","Language":"Korean","Country":"South Korea","Awards":"1 win & 1 nomination.","Poster":"https://m.media-amazon.com/images/M/MV5BZTllODRjMWUtMDAwMC00ZDBjLWFiYmQtYzgxMTc3NzcyZmVjXkEyXkFqcGdeQXVyMzE4MDkyNTA@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.1/10"}],"Metascore":"N/A","imdbRating":"7.1","imdbVotes":"199","imdbID":"tt3140006","Type":"series","totalSeasons":"1","Response":"True"
    },
    {"Title":"War","Year":"2007","Rated":"R","Released":"24 Aug 2007","Runtime":"103 min","Genre":"Action, Crime, Thriller","Director":"Philip G. Atwell","Writer":"Lee Anthony Smith, Gregory J. Bradley","Actors":"Jet Li, Jason Statham, John Lone, Devon Aoki","Plot":"An FBI Agent seeks vengeance on a mysterious assassin known as \"Rogue\" who murdered his partner.","Language":"English, Mandarin, Japanese, Cantonese","Country":"USA, Canada","Awards":"N/A","Poster":"https://m.media-amazon.com/images/M/MV5BNTIwMjE2Mjc1MF5BMl5BanBnXkFtZTYwNzI0OTI3._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.2/10"},{"Source":"Metacritic","Value":"36/100"}],"Metascore":"36","imdbRating":"6.2","imdbVotes":"85,455","imdbID":"tt0499556","Type":"movie","DVD":"05 Jun 2007","BoxOffice":"$22,486,409","Production":"New Glory Productions","Website":"N/A","Response":"True"
    },
    {"Title":"Harry Potter and the Deathly Hallows: Part 2","Year":"2011","Rated":"PG-13","Released":"15 Jul 2011","Runtime":"130 min","Genre":"Adventure, Drama, Fantasy, Mystery","Director":"David Yates","Writer":"Steve Kloves (screenplay), J.K. Rowling (novel)","Actors":"Ralph Fiennes, Michael Gambon, Alan Rickman, Daniel Radcliffe","Plot":"Harry, Ron, and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.","Language":"English","Country":"UK, USA","Awards":"Nominated for 3 Oscars. Another 46 wins & 91 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.1/10"},{"Source":"Rotten Tomatoes","Value":"96%"},{"Source":"Metacritic","Value":"85/100"}],"Metascore":"85","imdbRating":"8.1","imdbVotes":"761,228","imdbID":"tt1201607","Type":"movie","DVD":"N/A","BoxOffice":"$381,409,310","Production":"Heyday Films, Moving Picture Company, Warner Bros.","Website":"N/A","Response":"True"
    },
    {"Title":"The Invisible Guest","Year":"2016","Rated":"TV-MA","Released":"06 Jan 2017","Runtime":"106 min","Genre":"Crime, Drama, Mystery, Thriller","Director":"Oriol Paulo","Writer":"Oriol Paulo","Actors":"Mario Casas, Ana Wagener, Jose Coronado, Bárbara Lennie","Plot":"A successful entrepreneur accused of murder and a witness preparation expert have less than three hours to come up with an impregnable defense.","Language":"Spanish","Country":"Spain","Awards":"2 wins & 3 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMDk0YzAwYjktMWFiZi00Y2FmLWJmMmMtMzUyZDZmMmU5MjkzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.1/10"}],"Metascore":"N/A","imdbRating":"8.1","imdbVotes":"138,529","imdbID":"tt4857264","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"
    },
    {"Title":"In Time","Year":"2011","Rated":"PG-13","Released":"28 Oct 2011","imdbID":"tt414138","Runtime":"109 min","Genre":"Action, Sci-Fi, Thriller","Director":"Andrew Niccol","Writer":"Andrew Niccol","Actors":"Justin Timberlake, Olivia Wilde, Shyloh Oostwald, Johnny Galecki","Plot":"In a future where people stop aging at 25, but are engineered to live only one more year, having the means to buy your way out of the situation is a shot at immortal youth. Here, Will Salas finds himself accused of murder and on the run with a hostage - a connection that becomes an important part of the way against the system.","Language":"English","Country":"USA","Awards":"2 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjA3NzI1ODc1MV5BMl5BanBnXkFtZTcwMzI5NjQwNg@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.7/10"},{"Source":"Rotten Tomatoes","Value":"36%"},{"Source":"Metacritic","Value":"53/100"}],"Metascore":"53","imdbRating":"6.7","imdbVotes":"369,215","imdbID":"tt1637688","Type":"movie","DVD":"N/A","BoxOffice":"$37,520,095","Production":"New Regency Pictures, Strike Entertainment","Website":"N/A","Response":"True"
    },
    {"Title":"Titanic","Year":"1997","Rated":"PG-13","Released":"19 Dec 1997","Runtime":"194 min","Genre":"Drama, Romance","Director":"James Cameron","Writer":"James Cameron","Actors":"Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates","Plot":"A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.","Language":"English, Swedish, Italian, French","Country":"USA, Mexico","Awards":"Won 11 Oscars. Another 112 wins & 83 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.8/10"},{"Source":"Rotten Tomatoes","Value":"89%"},{"Source":"Metacritic","Value":"75/100"}],"Metascore":"75","imdbRating":"7.8","imdbVotes":"1,042,391","imdbID":"tt0120338","Type":"movie","DVD":"N/A","BoxOffice":"$659,363,944","Production":"20th Century Fox, Lightstorm Entertainment, Paramount Pictures","Website":"N/A","Response":"True"
    },
    {"Title":"ToY","Year":"2016","Rated":"TV-MA","Released":"N/A","Runtime":"93 min","Genre":"Drama, Romance","Director":"Patrick Chapman","Writer":"Patrick Chapman, Andrew Hanson (Writer), Andrew Hanson, Alissa Kokkins","Actors":"Briana Evigan, Bre Blair, Matt O'Leary, Darcy DeMoss","Plot":"Young L.A. artist, Chloe, hires prostitutes to pose nude and talk openly about their lives while she films them for her new art project. She falls for one of them, the elegant 40-something Kat. The two begin a tragic passionate affair.","Language":"English","Country":"USA","Awards":"2 wins.","Poster":"https://m.media-amazon.com/images/M/MV5BMTgyNDk3NDEwOV5BMl5BanBnXkFtZTgwODY5MTg5NzE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"5.4/10"},{"Source":"Rotten Tomatoes","Value":"62%"}],"Metascore":"N/A","imdbRating":"5.4","imdbVotes":"439","imdbID":"tt3530896","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"}
    ]
    
    export default movieDetail;